import type { GoalEntity } from "@/domain/entities/GoalEntity"
import type { TaskGroupEntity } from "@/domain/entities/TaskGroupEntity"
import type { TaskRuntimeEntity } from "@/domain/entities/TaskRuntimeEntity"
import type { DependencyEntity } from "@/domain/entities/DependencyEntity"
import type { EntitySnapshot } from "@/persistence/repository"
import type {
  GoalID,
  TaskID,
  TaskRuntimeID,
} from "@/domain/value-objects/types"
import { collectAncestorNodes } from "@/utils/dependency-tree"
import { hasTaskRuntimeForTask, isRepeatRuntime } from "@/utils/task-runtime"
import type { PlannerScope } from "../planner-service"

/**
 * Whether the given runtime is created by manual user input and thus should be preserved as-is during replan cycles, instead of being discarded and potentially regenerated by the planner.
 * @param runtime
 * @returns : true if the runtime is manual, false otherwise
 */
export function isManualRuntime(runtime: TaskRuntimeEntity): boolean {
  return runtime.source === "manual"
}

/**
 * Whether the given runtime should be preserved as-is in the next planner output
 * @param runtime
 * @param task
 * @param todayKey Date key of today, string in "YYYY-MM-DD" format
 * @param scope "full" lets step 5 re-pick default todos from scratch, so they are
 *              dropped here. "partial" skips step 5, so default todos must be kept
 *              to preserve today's plan.
 * @returns : true if the runtime should be preserved, false otherwise
 */
export function shouldPreserveRuntime(
  runtime: TaskRuntimeEntity,
  task: TaskGroupEntity | undefined,
  todayKey: string,
  scope: PlannerScope = "full"
): boolean {
  //--1.Manually added by the user — planner must never silently drop user intent.
  if (isManualRuntime(runtime)) {
    return true
  }

  //--2.Already acted on (in-progress / done / skipped) — historical fact, not re-derivable.
  if (runtime.arrangementStatus !== "todo") {
    return true
  }

  //--3.Repeat runtimes from past dates (debt points) — kept until resolved;
  // today's repeat points are dropped here and regenerated from the ledger in step 2.
  if (isRepeatRuntime(runtime)) {
    return task?.repeat != null && runtime.plannedForDate !== todayKey
  }

  //--4.Trigger runtimes are re-derived from trigger state every replan.
  if (runtime.source === "triggerPolicy") {
    return false
  }

  //--5.Remaining (default / duePolicy todos): full replan drops them so step 5
  // can re-pick from scratch; partial and focus replans keep them (focus only
  // drops the de-focused ones explicitly, partial keeps the plan frozen).
  return scope !== "full"
}

export function getTaskPlanMinutes(task: TaskGroupEntity): number {
  return task.estimatedDuration ?? 0
}

export function isTaskFinished(task: TaskGroupEntity): boolean {
  return task.completedCount >= task.total
}

export function compareTasks(
  left: TaskGroupEntity,
  right: TaskGroupEntity
): number {
  const leftDue = left.dueAt?.getTime() ?? Number.POSITIVE_INFINITY
  const rightDue = right.dueAt?.getTime() ?? Number.POSITIVE_INFINITY

  if (leftDue !== rightDue) {
    return leftDue - rightDue
  }

  const leftMinutes = getTaskPlanMinutes(left)
  const rightMinutes = getTaskPlanMinutes(right)
  if (leftMinutes !== rightMinutes) {
    return rightMinutes - leftMinutes
  }

  return left.title.localeCompare(right.title)
}
/**
 * Build a map of goal IDs to their associated taskGroup entities.
 * @param tasks Record snapshot for all taskGroup entities
 * @returns A map where the keys are goal IDs and the values are arrays of taskGroup entities associated with each goal.
 */
export function buildGoalTaskMap(
  tasks: Record<TaskID, TaskGroupEntity>
): Map<GoalID, TaskGroupEntity[]> {
  const map = new Map<GoalID, TaskGroupEntity[]>()

  for (const task of Object.values(tasks)) {
    if (!task.goalId) continue
    const list = map.get(task.goalId) ?? []
    list.push(task)
    map.set(task.goalId, list)
  }

  return map
}

export function buildGoalDependencyMap(
  deps: EntitySnapshot["deps"]
): Map<GoalID, DependencyEntity> {
  const map = new Map<GoalID, DependencyEntity>()

  for (const dep of Object.values(deps)) {
    map.set(dep.belongTo, dep)
  }

  return map
}

export function computeUsedMinutes(
  taskRuntime: Record<TaskRuntimeID, TaskRuntimeEntity>,
  tasks: Record<TaskID, TaskGroupEntity>
): number {
  let totalMinutes = 0

  for (const runtime of Object.values(taskRuntime)) {
    const task = tasks[runtime.taskId]
    if (!task) continue
    totalMinutes += getTaskPlanMinutes(task)
  }

  return totalMinutes
}

export function computeGoalRemainingMinutes(
  goalId: GoalID,
  goalTasks: Map<GoalID, TaskGroupEntity[]>,
  taskRuntime: Record<TaskRuntimeID, TaskRuntimeEntity>
): number {
  const tasks = goalTasks.get(goalId) ?? []
  let totalMinutes = 0

  for (const task of tasks) {
    if (task.repeat != null) continue
    if (isTaskFinished(task)) continue
    if (hasTaskRuntimeForTask(taskRuntime, task.id)) continue
    totalMinutes += getTaskPlanMinutes(task)
  }

  return totalMinutes
}

/**
 * Compares two goals for sorting purposes, based on due date, remaining work, and title. Used to determine the order of goals in the planner output.
 * @param left
 * @param right
 * @param goalTasks
 * @param taskRuntime
 * @returns  A negative number if left should come before right, a positive number if right should come before left, or 0 if they are considered equal.
 */
export function compareGoals(
  left: GoalEntity,
  right: GoalEntity,
  goalTasks: Map<GoalID, TaskGroupEntity[]>,
  taskRuntime: Record<TaskRuntimeID, TaskRuntimeEntity>
): number {
  const leftDue = left.dueAt?.getTime() ?? Number.POSITIVE_INFINITY
  const rightDue = right.dueAt?.getTime() ?? Number.POSITIVE_INFINITY

  if (leftDue !== rightDue) {
    return leftDue - rightDue
  }

  const leftRemaining = computeGoalRemainingMinutes(
    left.id,
    goalTasks,
    taskRuntime
  )
  const rightRemaining = computeGoalRemainingMinutes(
    right.id,
    goalTasks,
    taskRuntime
  )

  if (leftRemaining !== rightRemaining) {
    return rightRemaining - leftRemaining
  }

  return left.title.localeCompare(right.title)
}

export function areTaskAncestorsResolved(
  task: TaskGroupEntity,
  tasks: Record<TaskID, TaskGroupEntity>,
  dependency: DependencyEntity | undefined,
  scheduledTaskIds: Set<TaskID>
): boolean {
  if (!dependency) {
    return true
  }

  const ancestors = collectAncestorNodes(dependency, task.id)
  for (const ancestor of ancestors) {
    const ancestorTask = tasks[ancestor.node.data as TaskID]
    if (!ancestorTask) {
      continue
    }

    if (isTaskFinished(ancestorTask)) {
      continue
    }

    if (scheduledTaskIds.has(ancestorTask.id)) {
      continue
    }

    return false
  }

  return true
}

/**
 * Tasks at a goal's dependency frontier: unfinished, not already in the runtime,
 * with all ancestors *finished* (scheduled-but-unfinished does NOT count — the
 * selection takes the single top task of each chain and never descends within
 * one replan). `includeRuleTasks=false` drops repeat/trigger tasks, which skips
 * their whole chain (the walk does not reach past them to their dependents).
 */
export function selectGoalFrontierTasks(input: {
  goalTasks: TaskGroupEntity[]
  tasks: Record<TaskID, TaskGroupEntity>
  dependency: DependencyEntity | undefined
  nextTaskRuntime: Record<TaskRuntimeID, TaskRuntimeEntity>
  includeRuleTasks: boolean
}): TaskGroupEntity[] {
  // Empty set: areTaskAncestorsResolved then treats only *finished* ancestors as
  // resolved, so the frontier is one top task per chain (no descend).
  const finishedAncestorsOnly = new Set<TaskID>()
  return input.goalTasks.filter((task) => {
    if (isTaskFinished(task)) return false
    if (hasTaskRuntimeForTask(input.nextTaskRuntime, task.id)) return false
    if (
      !input.includeRuleTasks &&
      (task.repeat != null || task.trigger != null)
    ) {
      return false
    }
    return areTaskAncestorsResolved(
      task,
      input.tasks,
      input.dependency,
      finishedAncestorsOnly
    )
  })
}
